version: '3'

services:
  api:
    build: ./app
    ports:
    - "3003:3000"
    volumes:
    - "./app/server.js:/usr/src/app/sever.js"
    depends_on:
    - todos

  todos:
    build:
      context: ./todoapp
    ports:
      - "5000:5000"




