version: '3'

services:
  nodeapp:
    build: ./app
    ports:
    - "3000:3000"
    volumes:
    - "./app/server.js:/usr/src/app/sever.js"
    depends_on:
    - todoapp
    environment:
      - TODO_APP=http://todoApp:8080/

  todoapp:
    build: ./todo
    volumes:
      - ./todo/todos/todos.json:/app/todos.json




